version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: bddc-kafka-broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  backend:
    build:
      context: ./spring-kafka
    container_name: spring-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:29092
      # Configuration corrigée pour Kafka Streams
      - SPRING_CLOUD_STREAM_KAFKA_STREAMS_BINDER_BROKERS=broker:29092
      # Optionnel : configuration supplémentaire si nécessaire
      - SPRING_CLOUD_STREAM_KAFKA_STREAMS_BINDER_CONFIGURATION_COMMIT_INTERVAL_MS=1000
      - SPRING_CLOUD_STREAM_KAFKA_STREAMS_BINDER_CONFIGURATION_DEFAULT_KEY_SERDE=org.apache.kafka.common.serialization.Serdes$StringSerde
      - SPRING_CLOUD_STREAM_KAFKA_STREAMS_BINDER_CONFIGURATION_DEFAULT_VALUE_SERDE=org.springframework.kafka.support.serializer.JsonSerde
    depends_on:
      broker:
        condition: service_healthy
      zookeeper:
        condition: service_started
    restart: on-failure:5

  frontend:
    build:
      context: ./frontend
    container_name: react-ui
    ports:
      - "5173:80"
    depends_on:
      - backend